language: rust
rust:
# Nightly release channel
- nightly-2019-10-24

cache: cargo

matrix:
  fast_finish: true

before_script:
- rustup component add clippy
- rustup component add rustfmt

script:
- cargo clippy --all -- -D warnings
- cargo test --all
- cargo fmt --all -- --check
- rustup component add rust-src
- cargo install --force cargo-xbuild
- cargo install --force --path cargo-n64
# Create dummy IPL3 and build the example
- dd if=/dev/null of=/tmp/dummy-pl3 bs=4032 count=1
- cargo n64 build --ipl3 /tmp/dummy-ipl3 --package hello-ipl3font
